name: Reproduction
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        item:
          # Here you can add your fork of Renode
          - repository: 'https://github.com/renode/renode'
            revision: f1dd1b4af7838b45a925c17603cdfed0a583844a
            name: renode-baseline-f1dd1b4
          - repository: 'https://github.com/carlosqwqqwq/renode'
            revision: 248a61e3a677572b08417d52534b8bdf6afdd0cc
            name: renode-fixed-chain-248a61
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Configure git and artifacts dir
        run: |
          git config --global user.name "Antmicro"
          git config --global user.email "contact@antmicro.com"
      
      - uses: actions/download-artifact@v4
        with:
          name: build-results
          path: artifacts

      - name: Prepare Python dependencies
        run: pip3 install -r requirements.txt

      - name: Run tests on Renode
        uses: antmicro/renode-test-action@v5
        env:
          GIT_CONFIG_COUNT: ${{ matrix.item.name == 'renode-fixed-chain-248a61' && '2' || '0' }}
          GIT_CONFIG_KEY_0: url.https://github.com/carlosqwqqwq/renode-infrastructure.git.insteadOf
          GIT_CONFIG_VALUE_0: https://github.com/renode/renode-infrastructure.git
          GIT_CONFIG_KEY_1: url.https://github.com/carlosqwqqwq/tlib.git.insteadOf
          GIT_CONFIG_VALUE_1: https://github.com/antmicro/tlib.git
        with:
            renode-repository: ${{ matrix.item.repository }}
            renode-revision: ${{ matrix.item.revision }}
            tests-to-run: 'test.robot'

      - name: Archive Renode simulation results
        uses: actions/upload-artifact@v4
        with:
            name: test-results-${{ matrix.item.name }}
            path: |
                report.html
                log.html
                robot_output.xml

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Configure git and artifacts dir
        run: |
          git config --global user.name "Antmicro"
          git config --global user.email "contact@antmicro.com"

      - name: Run custom build.sh
        run: ./build.sh

      - name: Archive build results
        uses: actions/upload-artifact@v4
        with:
            name: build-results
            path: |
                artifacts
    
